### ISSUE TITLE
カレンダーのリデザイン

### ISSUE THREAD

**Issue by sKawashima** [ryu-g/web-miraibase#110]
カレンダーのデザインを一新するに当たって、開発目標となるデザインをつくってほしい

Slackはここから
https://mirai-base.slack.com/archives/CDPNF7FSQ/p1568866148000900

**Comment by ryu-g** [comment]
![SP-カレンダー](https://user-images.githubusercontent.com/9881744/65518353-2472e300-df1f-11e9-9358-4fb3056c5cf8.jpg)

SP版試作

**Comment by ryu-g** [comment]
イベント名がごちゃごちゃすんのどこまで許容するのかという問題が重い

**Comment by ryu-g** [comment]
書き出す画像間違えたので貼り直します

**Comment by ryu-g** [comment]
![SP-カレンダー](https://user-images.githubusercontent.com/9881744/65518910-0659b280-df20-11e9-8c67-c930681ad53c.jpg)

**Comment by ryu-g** [comment]
![PC-1](https://user-images.githubusercontent.com/9881744/65569985-90def800-df9a-11e9-9b5c-871aabdeeda3.jpg)

PC版

**変更点**
- 時間表記をAM/PMから24h表記へ変更
- 予定枠に白線を適用
- 週移動ボタン領域に"今日に戻る"ボタンを追加
- 終日予定領域の文字を"営業形態"に変更

**Comment by ryu-g** [comment]
![SP-1](https://user-images.githubusercontent.com/9881744/65570044-cbe12b80-df9a-11e9-9dc2-93c1657bfec1.jpg)
![SP-2](https://user-images.githubusercontent.com/9881744/65570045-cbe12b80-df9a-11e9-9eaa-dde7eae0fd72.jpg)
![SP-3](https://user-images.githubusercontent.com/9881744/65570046-cbe12b80-df9a-11e9-9b32-7f004fa837f7.jpg)

SP版x3 差分はボタンサイズ
**変更点**
- PC版と同じ部分(時間表記変更・予定枠に白線適用・今日に戻るボタン・終日予定テキスト変更)
- 週移動ボタンサイズを3パターン　個人的にはサイズ大がいいと思う

**Comment by ryu-g** [comment]
※1 マゼンタ破線
週移動ボタン・今日に戻るボタンの配置領域の右端について
画像ではスクロールバーの右端に設定してありますが、実装の都合でボタンを置ける場所が土曜日の右端のラインになってしまう場合は許容範囲

**Comment by sKawashima** [comment]
ぱっと見、線が多いなという印象
今日の部分だけ時間区切りの線が消えるってことで合ってる？

**Comment by sKawashima** [comment]
色使いはなるほどなという感じ
文字サイズとかの情報もよろしく

**Comment by ryu-g** [comment]
>その日の部分は時間区切りの線が消えるってことで合ってる？
薄緑色の領域が手前に来ちゃってた　時間区切りの線はあるていで作ってた
やっぱり線多いよね　もう少し色薄くしてみようかな

文字サイズ了解

**Comment by ryu-g** [comment]
![SP-1-guide](https://user-images.githubusercontent.com/9881744/65578656-2dac9000-dfb1-11e9-9924-0e6adeca9e03.jpg)

**変更点**
- 9月 を少し小さくした
- 罫線全体的に薄めに変更

こんなんでどうじゃろ

**Comment by sKawashima** [comment]
良くなっている
良くなると別のところが気になってくる

というわけで
・文字色#000000使う？
・スクロールバーは標準のこの太さで行く？多分弄れる

**Comment by ryu-g** [comment]
今別の作業やってるから18:30くらいにもう一回いじる
・時間部分確かに真っ黒じゃなくていいかも
・スクロールバーはとりあえずデフォでお願いします

**Comment by ryu-g** [comment]
![SP-1-guide](https://user-images.githubusercontent.com/9881744/65591651-ce0daf00-dfc7-11e9-91cf-7274925fedd3.jpg)

**変更点**
- 時間部分の色を変更(000 ▶ 5a5a5a)

日付のところは下記の観点からそのままにしてみた
- ハイコントラストできちんと数字を確認できるように
- 日付は`当日の営業状態`がセットになると思うので、見た目で`時間軸&指定時間帯イベント`の組み合わせと少しだけ差別化

**Comment by sKawashima** [comment]
良き。開発入るかな

![LGTM](https://user-images.githubusercontent.com/9900753/65606199-66fef300-dfe5-11e9-8547-4c0b4251d97f.gif)

**Comment by sKawashima** [comment]
@ryu-g あ、PC版も欲しい

**Comment by ryu-g** [comment]
@sKawashima そうだった　出します

**Comment by ryu-g** [comment]
![PC-2](https://user-images.githubusercontent.com/9881744/65695987-73ea1800-e0b3-11e9-8578-d3be5d66b2bf.jpg)

**前のPC版との変更点**
- 線と文字の色を調整(SP版と同じ)
- 月と日の配置をSP版に合わせました

**Comment by ryu-g** [comment]
▲画像修正した

**Comment by sKawashima** [comment]
![LGTM](https://user-images.githubusercontent.com/9900753/65698162-12c44380-e0b7-11e9-87ca-1aefd30829b7.png)
