### ISSUE TITLE
RFC: 文言が運営側目線なので調整したい

### ISSUE THREAD

**Issue by sKawashima** [ryu-g/web-miraibase#115]
#about にて、
```
函館で頑張るみんなの基地をめざして
MIRAI BASEは、現在函館で多方面に活躍する方々や、これから活躍していく方々の活動拠点となるための共同作業場です。
```
とあるが、これらは運営側がやろうとしてること。
見に来た人は「これはなんだろう」から入るので、運営目線の文言を外したくなった。
```
函館で頑張るみんなの基地
MIRAI BASEは、現在函館で多方面に活躍する方々や、これから活躍していく方々の活動拠点となる共同作業場です。
```

ただし、見出しのビジュアルがちょっと微妙になる
![miraibase jp_(Laptop with MDPI screen)](https://user-images.githubusercontent.com/9900753/67665045-37f4ec00-f9ac-11e9-8823-088688639a7e.png)

**Comment by ryu-g** [comment]
```
函館で頑張るみんなの基地
MIRAI BASEは、函館を活動拠点の一部とする様々な方にご利用いただける共同作業場です。
```

```
函館で頑張るみんなの基地
MIRAI BASEは、函館を活動拠点とする学生や社会人のみなさまにご利用いただける共同作業場です。
```

```
函館で頑張るみんなの基地
MIRAI BASEは、学生や社会人のみなさまの活動拠点としてご利用いただいている共同作業場です。
```


など？

**Comment by sKawashima** [comment]
> MIRAI BASEは、学生や社会人のみなさまの活動拠点としてご利用いただいている共同作業場です。
しれっと可能ではなく現在進行系、良いね
これに変えるの有りかもしれぬ

**Comment by ryu-g** [comment]
今MB運営やってる人たちにチェックしてもらってGoでたら反映かな

**Comment by sKawashima** [comment]
チェック依頼はPR作ってからかな
おけ

**Comment by sKawashima** [comment]
とりあえずPR作ったけど、これ誰にレビューしてもらえばいいんだ…？

**Comment by sKawashima** [comment]
とりあえず2019に投げるか

**Comment by ryu-g** [comment]
確かに誰にチェック通してもらえば良いのか謎だ　中ｍﾙﾙｧさん？

**Comment by sKawashima** [comment]
https://mirai-base.slack.com/archives/GMCAZUPFV/p1572667993022800
