### ISSUE TITLE
connpassからデータを持ってくる際のクエリの見直し

### ISSUE THREAD

**Issue by sKawashima** [ryu-g/web-miraibase#119]
# 問題
https://connpass.com/event/156703/ が表示されない
なぜなら、connpassのキーワード検索に引っかからないようなイベントだから

# 対処案（あれば）

キーワード検索ではなく他の検索クエリでもapiで捕まえられないか検証する

**Comment by ryu-g** [comment]
![スクリーンショット 2019-11-23 22 35 08](https://user-images.githubusercontent.com/9881744/69479526-8bd6e180-0e41-11ea-8d25-2833a975ef4c.png)
こういうこと？

**Comment by sKawashima** [comment]
そ

**Comment by sKawashima** [comment]
クエリ側でどうこうできる問題じゃないのでClose
