### ISSUE TITLE
MIRAIBASEへの連絡に関する領域をきちんと作る Contact

### ISSUE THREAD

**Issue by ryu-g** [ryu-g/web-miraibase#64]
# 問題
連絡先に関する下記の情報がfooterで初めて出てくるので、ユーザが情報を見落とすことが考えられる

# 対処案（あれば）
まとめてちゃんと領域を作る

```
section.contactArea
  見出し Contact
  p 電話番号
  p メールアドレス
  p Twitter
  p Facebook 
```
みたいな感じで

**Comment by ryu-g** [comment]
このissueからプルリクって作れるんだろうか

**Comment by sKawashima** [comment]
送れない。
けれど、ヒモ付は可能。
#67

**Comment by ryu-g** [comment]
なるほどね

**Comment by sKawashima** [comment]
コミットメッセージに `fix #64` みたいに書いとけば、マスターにマージされた瞬間このissueも閉じるのでオヌヌヌ
