### ISSUE TITLE
WPテンプレートに換装

### ISSUE THREAD

**Issue by ryu-g** [ryu-g/web-miraibase#7]

**Comment by ryu-g** [comment]
最初の公開、シングルページだしwp乗せる必要無い気がしてきたんだけどどう思う

**Comment by sKawashima** [comment]
有り
主にイベントの扱いを考えなきゃだが、とりあえずはそのままでもいいと思う

**Comment by ryu-g** [comment]
んだね テンプレート換装とwpインストールは複数ページ扱う仕組みに切り替わる時に考えるか
