### ISSUE TITLE
MIRAI BASEへのお問い合わせ部のリデザイン

### ISSUE THREAD

**Issue by sKawashima** [ryu-g/web-miraibase#87]
親：#77
# 問題
カレンダー仕様になるので営業日の記述が消えるのでそのあたり

- [ ] 営業時間の見せ方
- [ ] カレンダーの見出しの文言
- [ ] カレンダーを入れる場所

**Comment by ryu-g** [comment]
確かに

作っときます

**Comment by ryu-g** [comment]
できたら画像でここに貼ります

**Comment by ryu-g** [comment]
![スクリーンショット 2019-08-13 18 21 14](https://user-images.githubusercontent.com/9881744/62930353-35481900-bdf7-11e9-8094-60237d695790.png)
フッターにも営業時間に言及してるテキストあるから、変更するなり消すなりが必要ですわ

**Comment by ryu-g** [comment]
・アンカーに「営業時間はカレンダーをご確認ください」書いて、カレンダーを表示してるsectionに飛ばす
・営業時間に関する場所消す　消して何もしない
・毎月営業日を予め設定し公開する旨を書く

など

**Comment by ryu-g** [comment]
![スクリーンショット 2019-08-14 18 38 21](https://user-images.githubusercontent.com/9881744/63011308-08613800-bec3-11e9-800c-c38eb6435f8c.png)

**Comment by ryu-g** [comment]
こんな感じにするのが良いかな？
