### ISSUE TITLE
2019-08-15目標で公開するリニューアル告知ページの作成

### ISSUE THREAD

**Issue by deckeye** [ryu-g/web-miraibase#89]
# 問題
2019-09-01 にMIRAI BASEの運営形態が変更される旨の告知を行いたいが、行う場所を用意していない。

# 対処案（あれば）
1. リニューアル告知ページ(もしくはコーナー)を作成し、告知を行う
2. 告知を行っている旨、トップページでも紹介する

**Comment by ryu-g** [comment]
- ドロップインの営業形態の変更
- 毎週金曜日(14:00-22:00)は定期営業日
- その他は不定期営業
  - 営業日はWEBサイト上のカレンダーに適宜記入
- 貸し会議室は、完全予約制に変更

**Comment by sKawashima** [comment]
bahoに感謝
内容：

## 概要
- ドロップインでの営業を縮小
- 会員制の導入
- 会議室は完全予約制へ移行
- (既存利用者へ)ドロップインの一般利用料金変更
## 変更後の営業形態
### ドロップイン
 - 毎週金曜日(14:00-22:00)のみ営業
 - 学生料金 : 2h 100円, 最大料金 300円
 - 一般料金 : 2h 500円, 最大料金 1000円
### 会員制
 - 基本 平日(10:00-19:00)営業
   - 営業日はWebサイトのカレンダーを参照
 - 通常利用料金 1万/月
 - 専用ロッカー付利用料金 2万/月
### 完全予約制
 - 会議室スペース
 - 料金 : 1800円/日

**Comment by sKawashima** [comment]
#77 を更に広げる？

**Comment by sKawashima** [comment]
じゃんぼさんからの最新版

## 変更後の営業形態(9/1から適用)
### コワーキングスペース ドロップイン
- 毎週金曜日(14:00-22:00)のみ営業(祝日は除く)
- 学生料金 : 2h 100円, 最大料金 300円
- 一般料金 : 2h 500円, 最大料金 1000円
### コワーキングスペース 会員制
- 基本 平日(10:00-19:00)営業
 - 営業日は、Webサイトのカレンダーを参照
- 通常利用料金 : 1万/月
- 専用ロッカー付利用料金 : 2万/月
### 貸会議室 完全予約制
- 料金 : 500円/1h
### イベント貸切スペース
- 平日・休日・祝日問わず応相談
- 学生料金 : 700円/1h
- 一般料金 : 3000円/1h

**Comment by ryu-g** [comment]
イベント貸し切りスペースってasovivaとsigotovaどっちですかね　もしか、
webの貸し切り利用欄からsigotovaが消える？
