### ISSUE TITLE
トップページ冒頭部分を、利用者が自然と下にスクロールしようとする感じにしたい

### ISSUE THREAD

**Issue by deckeye** [ryu-g/web-miraibase#90]
# 問題
サイト利用者が、ロゴが出ているトップページの上部をローディング画面と思い込んでしまい、しばらく待ってしまった、との報告を高専の学生の吉田さんから聞いたため。

問題、とまで行くような内容かはわかりませんが、フィードバックがありましたので報告します。

# 対処案（あれば）

**Comment by ryu-g** [comment]
これは確かにあるかもしれないですね
考えてみます

**Comment by ryu-g** [comment]
カレンダーとか営業時間の指定が変わる旨の説明とか、あのへんの機能な部分が終わったら

**Comment by sKawashima** [comment]
初期案で▼下に置くのあった気がするよね

**Comment by ryu-g** [comment]
![スクリーンショット 2019-08-27 19 18 41](https://user-images.githubusercontent.com/9881744/63763804-70bb0b00-c900-11e9-9037-5f7600a6955e.png)

**Comment by ToshihitoKon** [comment]
MIRAI BASEのロゴの下の部分が矢印っぽいので、1の一番左のやつの隙間をもう少し開けたらいい感じにマッチしそう

**Comment by ryu-g** [comment]
cssからPCとSPで表示を切り替える可能性を視野に入れています
まだ構想段階だけど、animaitonでの実装が軽くていいかなとおもっている

**Comment by ryu-g** [comment]
>MIRAI BASEのロゴの下の部分が矢印っぽいので、1の一番左のやつの隙間をもう少し開けたらいい感じにマッチしそう

ね、ちょっと考えてた　
懸念があるとすると、MBのロゴの下の方にあるちょんちょんってやつ、中央の正方形が上昇・拡大しているイメージで作っている(情報のベクトルが上向き)ので、今回下向きに誘導するのと差別化したほうが良いのかあとか、見た目的にマッチしてればかっこよく見えるかな？どうしようかな？とか悩み中　候補が増えてきた段階で相談したいところ
